
package org.firebird.monitor.view;

import org.firebird.monitor.control.LogSQLControl;


public class LogSQLView extends javax.swing.JDialog {

    private LogSQLControl ls;

    public LogSQLView(java.awt.Frame parent, boolean modal, LogSQLControl l) {
        super(parent, modal);
        this.ls = l;
        initComponents();
    }

    public void addLogSQL(String log) {        
        this.logSQLjTextArea.append(log);
        logSQLjTextArea.select(1, 1);
    }

    public void clearLogSQL() {
        this.logSQLjTextArea.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        logSQLjTextArea = new javax.swing.JTextArea();
        loadLogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log SQL");

        logPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Log SQL "));
        logPanel.setName(""); // NOI18N

        logSQLjTextArea.setColumns(20);
        logSQLjTextArea.setEditable(false);
        logSQLjTextArea.setRows(5);
        jScrollPane3.setViewportView(logSQLjTextArea);
        logSQLjTextArea.getAccessibleContext().setAccessibleParent(logPanel);

        loadLogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/fldr_obj.gif"))); // NOI18N
        loadLogButton.setText("Load Log");
        loadLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadLogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
            .addGroup(logPanelLayout.createSequentialGroup()
                .addComponent(loadLogButton)
                .addContainerGap(538, Short.MAX_VALUE))
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadLogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logPanel.getAccessibleContext().setAccessibleName(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadLogButtonActionPerformed
        ls.loadLogSQL();
    }//GEN-LAST:event_loadLogButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton loadLogButton;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea logSQLjTextArea;
    // End of variables declaration//GEN-END:variables
}
