
package org.firebird.monitor.view;

import javax.swing.table.DefaultTableModel;
import org.firebird.monitor.control.MonitorControl;
import javax.swing.Icon;

public class MonitorView extends javax.swing.JFrame {

    private MonitorControl mc;
    private Icon icon;

    public MonitorView(MonitorControl m) {
        initComponents();
        timejSpinner.setValue(2);
        mc = m;
        startstopjButton.grabFocus();
    }

    public DefaultTableModel getTableModelConnections() {
        return (DefaultTableModel) connectionsjTable.getModel();
    }

    public DefaultTableModel getTableModelTransactions() {
        return (DefaultTableModel) transactionsjTable.getModel();
    }

    public void setDatabaseName(String database) {
        databaseNamejLabel.setText(database);
    }

    public void setSql(String sql) {
        sqljTextArea.setText(sql);
        sqljTextArea.select(1, 1);
    }

    public void setDeletes(Long deletes) {
        deletesjLabel.setText(String.valueOf(deletes));
    }

    public void setInserts(Long inserts) {
        insertsjLabel.setText(String.valueOf(inserts));
    }

    public void setUpdates(Long updates) {
        updatesjLabel.setText(String.valueOf(updates));
    }

    public void setPageReads(String reads) {
        readsjLabel.setText(reads);
    }

    public int getTimeUpdate() {
        return (Integer) timejSpinner.getValue() * 1000;
    }

    public void chooseRegistration() {
        mc.openRegistrations();
    }

    public boolean getChooseTransaction() {
        return chooseTransactionjCheckBox.isSelected();
    }

    public boolean getChooseAttachment() {
        return chooseAttachmentjCheckBox.isSelected();
    }

    public void setStartButton() {
        startstopjButton.setText("Start Monitor");
        icon = startstopjButton.getIcon();
        startstopjButton.setIcon(startstopjButton.getPressedIcon());
        startstopjButton.setPressedIcon(icon);
    }

    public void setStopButton() {
        startstopjButton.setText("Stop Monitor");
        icon = startstopjButton.getIcon();
        startstopjButton.setIcon(startstopjButton.getPressedIcon());
        startstopjButton.setPressedIcon(icon);
    }

    public void setTransactionLabel(int transaction) {
        tituloSQLjLabel.setText("Command SQL from Transaction Nr.: " + transaction);
    }

    public void setNumberAttachments(int n) {
        chooseAttachmentjCheckBox.setText("Choose Connection(" + n + ")");
    }

    public void setNumberTransactions(int n) {
        chooseTransactionjCheckBox.setText("Choose Transaction(" + n + ")");
    }

    public void viewLogSQL() {
        mc.openLogSQL();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        connectionsjTable = new javax.swing.JTable();
        cancelConnectionjButton = new javax.swing.JButton();
        chooseAttachmentjCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionsjTable = new javax.swing.JTable();
        tituloSQLjLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        sqljTextArea = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        insertsjLabel = new javax.swing.JLabel();
        updatesjLabel = new javax.swing.JLabel();
        deletesjLabel = new javax.swing.JLabel();
        cancelCommandjButton = new javax.swing.JButton();
        chooseTransactionjCheckBox = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        readsjLabel = new javax.swing.JLabel();
        startstopjButton = new javax.swing.JButton();
        timejSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        databaseNamejLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registrationsjMenuItem = new javax.swing.JMenuItem();
        logSQLjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        aboutjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jMonitorFirebird");
        setFont(new java.awt.Font("Verdana", 0, 11));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Connections ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        connectionsjTable.setFont(new java.awt.Font("Verdana", 0, 11));
        connectionsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "State", "Time", "Attach"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        connectionsjTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        connectionsjTable.getTableHeader().setReorderingAllowed(false);
        connectionsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                connectionsjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(connectionsjTable);
        connectionsjTable.getColumnModel().getColumn(0).setMinWidth(100);
        connectionsjTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        connectionsjTable.getColumnModel().getColumn(0).setMaxWidth(100);
        connectionsjTable.getColumnModel().getColumn(1).setMinWidth(45);
        connectionsjTable.getColumnModel().getColumn(1).setPreferredWidth(45);
        connectionsjTable.getColumnModel().getColumn(1).setMaxWidth(45);
        connectionsjTable.getColumnModel().getColumn(2).setMinWidth(65);
        connectionsjTable.getColumnModel().getColumn(2).setPreferredWidth(65);
        connectionsjTable.getColumnModel().getColumn(2).setMaxWidth(65);
        connectionsjTable.getColumnModel().getColumn(3).setMinWidth(60);
        connectionsjTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        connectionsjTable.getColumnModel().getColumn(3).setMaxWidth(60);

        cancelConnectionjButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancelConnectionjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/showerr_tsk.gif"))); // NOI18N
        cancelConnectionjButton.setText("Cancel Connection");
        cancelConnectionjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelConnectionjButtonActionPerformed(evt);
            }
        });

        chooseAttachmentjCheckBox.setFont(new java.awt.Font("Verdana", 1, 11));
        chooseAttachmentjCheckBox.setText("Choose Connection");
        chooseAttachmentjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAttachmentjCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(cancelConnectionjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseAttachmentjCheckBox))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(chooseAttachmentjCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelConnectionjButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Transactions ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Verdana", 0, 11));

        transactionsjTable.setFont(new java.awt.Font("Verdana", 0, 11));
        transactionsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "State", "Time", "Isolation Mode", "Timeout", "Attach", "Transaction", "User", "Stat Id", "Read Only", "Auto Commit", "Auto Undo", "Remote Process"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionsjTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        transactionsjTable.getTableHeader().setReorderingAllowed(false);
        transactionsjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionsjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(transactionsjTable);
        transactionsjTable.getColumnModel().getColumn(0).setMinWidth(50);
        transactionsjTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        transactionsjTable.getColumnModel().getColumn(0).setMaxWidth(50);
        transactionsjTable.getColumnModel().getColumn(1).setMinWidth(45);
        transactionsjTable.getColumnModel().getColumn(1).setPreferredWidth(45);
        transactionsjTable.getColumnModel().getColumn(1).setMaxWidth(45);
        transactionsjTable.getColumnModel().getColumn(2).setMinWidth(65);
        transactionsjTable.getColumnModel().getColumn(2).setPreferredWidth(65);
        transactionsjTable.getColumnModel().getColumn(2).setMaxWidth(65);
        transactionsjTable.getColumnModel().getColumn(3).setMinWidth(200);
        transactionsjTable.getColumnModel().getColumn(3).setPreferredWidth(200);
        transactionsjTable.getColumnModel().getColumn(3).setMaxWidth(200);
        transactionsjTable.getColumnModel().getColumn(4).setMinWidth(150);
        transactionsjTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        transactionsjTable.getColumnModel().getColumn(4).setMaxWidth(150);
        transactionsjTable.getColumnModel().getColumn(5).setMinWidth(60);
        transactionsjTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        transactionsjTable.getColumnModel().getColumn(5).setMaxWidth(60);
        transactionsjTable.getColumnModel().getColumn(6).setMinWidth(80);
        transactionsjTable.getColumnModel().getColumn(6).setPreferredWidth(80);
        transactionsjTable.getColumnModel().getColumn(6).setMaxWidth(80);
        transactionsjTable.getColumnModel().getColumn(7).setMinWidth(90);
        transactionsjTable.getColumnModel().getColumn(7).setPreferredWidth(90);
        transactionsjTable.getColumnModel().getColumn(7).setMaxWidth(90);
        transactionsjTable.getColumnModel().getColumn(8).setMinWidth(70);
        transactionsjTable.getColumnModel().getColumn(8).setPreferredWidth(70);
        transactionsjTable.getColumnModel().getColumn(8).setMaxWidth(70);
        transactionsjTable.getColumnModel().getColumn(9).setMinWidth(70);
        transactionsjTable.getColumnModel().getColumn(9).setPreferredWidth(70);
        transactionsjTable.getColumnModel().getColumn(9).setMaxWidth(70);
        transactionsjTable.getColumnModel().getColumn(10).setMinWidth(80);
        transactionsjTable.getColumnModel().getColumn(10).setPreferredWidth(80);
        transactionsjTable.getColumnModel().getColumn(10).setMaxWidth(80);
        transactionsjTable.getColumnModel().getColumn(11).setMinWidth(80);
        transactionsjTable.getColumnModel().getColumn(11).setPreferredWidth(80);
        transactionsjTable.getColumnModel().getColumn(11).setMaxWidth(80);
        transactionsjTable.getColumnModel().getColumn(12).setMinWidth(400);
        transactionsjTable.getColumnModel().getColumn(12).setPreferredWidth(400);
        transactionsjTable.getColumnModel().getColumn(12).setMaxWidth(400);

        tituloSQLjLabel.setFont(new java.awt.Font("Verdana", 1, 11));
        tituloSQLjLabel.setText("Command SQL");

        sqljTextArea.setColumns(20);
        sqljTextArea.setEditable(false);
        sqljTextArea.setRows(5);
        jScrollPane3.setViewportView(sqljTextArea);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel21.setText("Inserts:");

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel22.setText("Updates:");

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel23.setText("Deletes:");

        insertsjLabel.setFont(new java.awt.Font("Verdana", 0, 11));
        insertsjLabel.setText(".............");

        updatesjLabel.setFont(new java.awt.Font("Verdana", 0, 11));
        updatesjLabel.setText(".............");

        deletesjLabel.setFont(new java.awt.Font("Verdana", 0, 11));
        deletesjLabel.setText(".............");

        cancelCommandjButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cancelCommandjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/showerr_tsk.gif"))); // NOI18N
        cancelCommandjButton.setText("Cancel Command");
        cancelCommandjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCommandjButtonActionPerformed(evt);
            }
        });

        chooseTransactionjCheckBox.setFont(new java.awt.Font("Verdana", 1, 11));
        chooseTransactionjCheckBox.setText("Choose Transaction");
        chooseTransactionjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTransactionjCheckBoxActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel24.setText("Reads:");

        readsjLabel.setFont(new java.awt.Font("Verdana", 0, 11));
        readsjLabel.setText(".............");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addComponent(chooseTransactionjCheckBox)
                    .addComponent(cancelCommandjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tituloSQLjLabel)
                        .addContainerGap(498, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(insertsjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(updatesjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(deletesjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(readsjLabel)
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chooseTransactionjCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(insertsjLabel)
                    .addComponent(jLabel22)
                    .addComponent(updatesjLabel)
                    .addComponent(deletesjLabel)
                    .addComponent(jLabel24)
                    .addComponent(readsjLabel)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloSQLjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelCommandjButton)
                .addContainerGap())
        );

        startstopjButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        startstopjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/activity.gif"))); // NOI18N
        startstopjButton.setText("Start Monitor");
        startstopjButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/progress_stop.gif"))); // NOI18N
        startstopjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startstopjButtonActionPerformed(evt);
            }
        });

        timejSpinner.setFont(new java.awt.Font("Verdana", 0, 11));
        timejSpinner.setBorder(null);
        timejSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(timejSpinner, ""));
        timejSpinner.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel2.setText("Refresh:");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel8.setText("Database Name:");

        databaseNamejLabel.setFont(new java.awt.Font("Verdana", 0, 11));
        databaseNamejLabel.setText("...");

        jMenu1.setText("File");

        registrationsjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/new_persp.gif"))); // NOI18N
        registrationsjMenuItem.setText("Registrations");
        registrationsjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationsjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(registrationsjMenuItem);

        logSQLjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/configs.gif"))); // NOI18N
        logSQLjMenuItem.setText("Log SQL");
        logSQLjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logSQLjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logSQLjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        aboutjMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/firebird/monitor/image/info_tsk.gif"))); // NOI18N
        aboutjMenuItem.setText("About");
        aboutjMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutjMenuItemMouseClicked(evt);
            }
        });
        aboutjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(aboutjMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(startstopjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(databaseNamejLabel))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(timejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startstopjButton)
                    .addComponent(jLabel8)
                    .addComponent(databaseNamejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelCommandjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCommandjButtonActionPerformed
        // TODO add your handling code here:
        mc.cancelStatement();
}//GEN-LAST:event_cancelCommandjButtonActionPerformed

    private void cancelConnectionjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelConnectionjButtonActionPerformed
        // TODO add your handling code here:
        mc.cancelConnection();
}//GEN-LAST:event_cancelConnectionjButtonActionPerformed

    private void chooseTransactionjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTransactionjCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chooseTransactionjCheckBoxActionPerformed

    private void transactionsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsjTableMouseClicked
        // TODO add your handling code here:
        if (getChooseTransaction()) {
            try {
                mc.setTransactionId(Integer.valueOf(transactionsjTable.getValueAt(transactionsjTable.getSelectedRow(), 6).toString()));
                mc.setStatId(Integer.valueOf(transactionsjTable.getValueAt(transactionsjTable.getSelectedRow(), 8).toString()));
                mc.refreshMonitorView();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_transactionsjTableMouseClicked

    private void aboutjMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutjMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutjMenuItemMouseClicked

    private void aboutjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutjMenuItemActionPerformed
        // TODO add your handling code here:
        mc.openAbout();
    }//GEN-LAST:event_aboutjMenuItemActionPerformed

    private void registrationsjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationsjMenuItemActionPerformed
        // TODO add your handling code here:
        chooseRegistration();
    }//GEN-LAST:event_registrationsjMenuItemActionPerformed

    private void chooseAttachmentjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAttachmentjCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chooseAttachmentjCheckBoxActionPerformed

    private void connectionsjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectionsjTableMouseClicked
        // TODO add your handling code here:
        if (getChooseAttachment()) {
            try {
                mc.setAttachmentId(Integer.valueOf(connectionsjTable.getValueAt(connectionsjTable.getSelectedRow(), 3).toString()));
                mc.refreshMonitorView();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_connectionsjTableMouseClicked

    private void startstopjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startstopjButtonActionPerformed
        // TODO add your handling code here:
        if (mc.isConnected()) {
            if (mc.getMonitoring()) {
                mc.setStopMonitoring();
            } else {
                mc.setStartMonitoring();
            }
        }
}//GEN-LAST:event_startstopjButtonActionPerformed

    private void logSQLjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logSQLjMenuItemActionPerformed
        // TODO add your handling code here:
        viewLogSQL();
    }//GEN-LAST:event_logSQLjMenuItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutjMenuItem;
    private javax.swing.JButton cancelCommandjButton;
    private javax.swing.JButton cancelConnectionjButton;
    private javax.swing.JCheckBox chooseAttachmentjCheckBox;
    private javax.swing.JCheckBox chooseTransactionjCheckBox;
    private javax.swing.JTable connectionsjTable;
    private javax.swing.JLabel databaseNamejLabel;
    private javax.swing.JLabel deletesjLabel;
    private javax.swing.JLabel insertsjLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem logSQLjMenuItem;
    private javax.swing.JLabel readsjLabel;
    private javax.swing.JMenuItem registrationsjMenuItem;
    private javax.swing.JTextArea sqljTextArea;
    private javax.swing.JButton startstopjButton;
    private javax.swing.JSpinner timejSpinner;
    private javax.swing.JLabel tituloSQLjLabel;
    private javax.swing.JTable transactionsjTable;
    private javax.swing.JLabel updatesjLabel;
    // End of variables declaration//GEN-END:variables
}
